### ISSUE TITLE
Update for .NET 8.0

### ISSUE THREAD

**Issue by CSTrombone** [mikelor/Chaaos#3]
So what is done to fix the xml problem with .NET 8.0?

I see that you've made an update but I cant seem to find any differences, it could be that I'm blind (and I am definitely stupid), but what was the fix?

**Comment by mikelor** [comment]
Here's the actual commit with the changes to the .csproj file.
https://github.com/mikelor/Chaaos/commit/11be3de44407ee10f6a92f6cbfa481961c387db7

Did it work for you?

**Comment by CSTrombone** [comment]
I can't really figure out how to read that tbh

**Comment by mikelor** [comment]
It's just a diff of the .csproj file (Red is deletes, Green is added). I basically updated to .NET 8, and then added a package reference.
```
		<!-- Fix for https://github.com/dotnet/maui/issues/18665 -->
		<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.6.2" />
```
Good luck.

**Comment by CSTrombone** [comment]
I still can't get everything to work properly, but I removed all of the
errors by simply deleting one line. There was one stupid line that was
going out of its way to delete the XML file every time I made it. I have no
idea how it got there now it rebuilds perfectly fine

**Comment by CSTrombone** [comment]
How do you get it to show up in android auto? Mine is the same, and the app can install to my phone, but it never shows up in android auto at all. Not even the app list is settings.

**Comment by mikelor** [comment]
Can you post your code to a repository?
Double check your manifest settings.

**Comment by CSTrombone** [comment]
Yeah, I can. Give me a few

**Comment by CSTrombone** [comment]
https://github.com/CSTrombone/AAapp.git

Here you go good sir. I'm 120% Sure I did something wrong, but I cannot for the life of me find out what.

**Comment by CSTrombone** [comment]
Does your app still show up in Android Auto?

**Comment by CSTrombone** [comment]
Guess not

**Comment by mikelor** [comment]
Sorry, I missed this. I'll take a look, but traveling at the moment.

I'm heading to Antarctica until end of February. I'll have connectivity, but unsure about tinlme.

**Comment by mikelor** [comment]
I dint see the repo. Did you make it public?

**Comment by CSTrombone** [comment]
> I dont see the repo. Did you make it public? 

I made it public but it says it's private. I don't see a way to make it public.

**Comment by mikelor** [comment]
Unfortunately I can no longer get to github. May have to wait until end of
Feb. :(

**Comment by CSTrombone** [comment]
Well whenever you can make it back, it is now public :)

**Comment by mikelor** [comment]
Hey, I'm back and took a look at your project. I tried to do a git clone and compile it, but it didn't work right of the bat. If it runs and compiles for you, then you should be fine. In looking at your code, I think I found the problem.

In your /Platforms/Android/Auto/Services/CarService.cs file you are using mixed case for the [IntentFilter] attribute, it needs to be all lower case.

`   [IntentFilter(new string[] { "androidx.car.app.CarAppService" }, Categories = new[] { "androidx.car.app.category.POI" })]
`
Instead of
`   [IntentFilter(new string[] { "androidX.Car.App.CarAppService" }, Categories = new[] { "androidx.car.app.category.POI" })]
`
I created a workable project for you here https://github.com/mikelor/YouTubeControl 
I initially thought the "space" in your project was causing the issue.

See screenshots
![YouTubeControlInAA](https://github.com/mikelor/Chaaos/assets/341942/872cc226-efbd-4543-baff-32b71fd7238f)
![YouTubeControlScreen](https://github.com/mikelor/Chaaos/assets/341942/66e0b3f5-d807-4885-a583-ffa0ed7f956b)

Hope this helps. Happy to chat if needed.

**Comment by CSTrombone** [comment]
Holy crap thanks! I'll check this one in a bit, I bet that is the problem!

Thanks for responding!

**Comment by CSTrombone** [comment]
So after making the same changes you did, it still isn't working for me. I went ahead and loaded up your workable version you made and it works perfectly fine, first try. There are genuinely no differences between yours and mine. They are identical in every way imaginable. I combed through every single file in the whole project. They are 1 to 1 copies, yet mine doesn't work and yours does. This is very confusing. I'm just going to build off of the working one, but I am so confused.

**Comment by mikelor** [comment]
Weird. If you want please commit your exact copy to source girhub and I'll
try and compile and run it. Its got to be something small and simple.

Also what version of Visual Studio

**Comment by CSTrombone** [comment]
Alright, I updated my repository with the current version after copying your code verbatim. No idea what could be missing.

https://github.com/CSTrombone/AAapp.git

**Comment by mikelor** [comment]
As I said earler, In your /Platforms/Android/Auto/Services/CarService.cs file you are using mixed case for the [IntentFilter] attribute, it needs to be all lower case. Change Line 14 so that it looks like this. :)
  [IntentFilter(new string[] { "androidx.car.app.CarAppService" }, Categories = new[] { "androidx.car.app.category.POI" })]

Once I changed this line, I YTControl shows up in Android Auto. Hurray! Please let me know if it works for you.

**Comment by mikelor** [comment]
Essentially change "androidX" to "androidx" leave everything else the same.
